name: gyant-dcl

services:

  frontend:
    container_name: dcl-frontend
    build: images/frontend/.
    ports:
      - "3000:3000"
    #environment:
    #  - REACT_APP_BACKEND_PORT=4000

  backend:
    container_name: dcl-backend
    build: images/backend/.
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=dockercompose
    #  - NODE_DATABASE_PORT=27017

  database:
    container_name: dcl-database
    build: images/database/.
    ports:
      - "27017:27017"
